services:
  # PostgreSQL Database
  mes-database:
    image: postgres:15-alpine
    container_name: mes-database
    environment:
      POSTGRES_DB: mes_production
      POSTGRES_USER: mes_user
      POSTGRES_PASSWORD: mes_secure_password_2024
    volumes:
      - mes_db_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mes_user -d mes_production"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend API Service
  mes-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mes-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mes-database
      - DB_PORT=5432
      - DB_NAME=mes_production
      - DB_USER=mes_user
      - DB_PASSWORD=mes_secure_password_2024
    depends_on:
      mes-database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 3001, path: '/api/working-hours', timeout: 2000 }; const req = http.request(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  mes-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mes-frontend
    ports:
      - "80:80"
    depends_on:
      - mes-backend
      - mes-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional - for production)
  nginx-proxy:
    image: nginx:alpine
    container_name: mes-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mes-frontend
      - mes-backend
    restart: unless-stopped
    profiles:
      - production

  # Webhook Server (Optional - for auto-deployment)
  webhook-server:
    image: node:18-alpine
    container_name: mes-webhook
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    working_dir: /app
    command: node scripts/webhook-server.js
    restart: unless-stopped
    profiles:
      - webhook

# Volumes for persistent data
volumes:
  mes_db_data:
    driver: local
